_project/urls.py
from django.apps import apps as django_apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^staff_area/', include('apps.shop.urls_for_staff',
                                 namespace='staff_area')),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^search/', include('haystack.urls')),

    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^order/', include('apps.orders.urls', namespace='order')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^coupons/', include('apps.coupons.urls', namespace='coupon')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^', include('apps.shop.urls', namespace='shop'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rosetta_is_installed = django_apps.is_installed('rosetta')
if rosetta_is_installed:
    urlpatterns = [
        url(r'^rosetta/', include('rosetta.urls')),
    ] + urlpatterns

# ___________________________________________________________________________
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

apps/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.cart_detail,
        name='detail'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove_product,
        name='remove_product'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add_product,
        name='add_product'),
    url(r'^clear/$',
        views.cart_clear,
        name='clear')
]

apps/coupons/urls.py
from django.conf.urls import url

from . import views, views_for_staff

urlpatterns = [
    url(r'^apply/$',
        views.coupon_apply,
        name='apply'),

    url(r'^list/$',
        views_for_staff.coupons,
        name='list'),
    url(r'^create/$',
        views_for_staff.coupon_create,
        name='create'),
]

apps/orders/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^create/$', views.order_create, name='create'),

    url(r'^admin/order/(?P<order_id>\d+)/$',
        views.admin_order_detail,
        name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$',
        views.admin_order_pdf,
        name='admin_order_pdf'),
]

apps/shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main, name='main_page'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^product_detail/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<manufacturer_slug>[-\w]+)/$',
        views.product_list_by_manufacturer,
        name='product_list_by_manufacturer'),
]

apps/cart/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ..shop.models import Product


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label=_('Qty'), choices=[], coerce=int)
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        product_id = kwargs.pop('product_id')
        super(CartAddProductForm, self).__init__(*args, **kwargs)
        product = Product.objects.filter(id=product_id).first()
        choices = [(i, str(i)) for i in range(1, product.stock + 1)]
        self.fields['quantity'].choices = choices

apps/cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from ..coupons.forms import CouponApplyForm
from ..shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add_product(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST, product_id=product_id)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update'])
    return redirect('cart:detail')


def cart_remove_product(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        product = item['product']
        item['update_quantity_form'] = CartAddProductForm(
                                        product_id=product.id,
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    context = {'cart': cart, 'coupon_apply_form': CouponApplyForm()}
    return render(request, 'cart/detail.html', context)


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('shop:main_page')

templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}
  Ваш кошик товарів
{% endblock %}

{% block content %}
<section class="container" id="main">
  <div class="wrapper">
    <h4>Ваш кошик товарів</h4>
    <div class="row">
      <table class="cart u-full-width">
        <thead>
          <tr>
            <th>Продукт</th>
            <th>К-сть</th>
            <th>Ціна, грн</th>
            <th>Вартість, грн</th>
            <th>-</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    {{ product.name }} <br>
                    {{ product.model_name }} <br>
                    <img src="{{ product.main_image.url }}" alt="" />
                  </a>
                </td>
                <td>
                  <form action="{% url 'cart:add_product' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Оновити">
                  </form>
                </td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
                <td>
                  <a href="{% url 'cart:remove_product' product.id %}">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  </a>
                </td>
              </tr>
            {% endwith %}
          {% endfor %}
            {% if cart.coupon %}
            <tr class="subtotal">
              <td>Сумма без знижки</td>
              <td colspan="3"></td>
              <td>{{ cart.get_total_price }}</td>
            </tr>
            <tr>
              <td>
                "{{ cart.coupon.code }}" купон на знижку {{ cart.coupon.discount }}%
              </td>
              <td colspan="3"></td>
              <td>{{ cart.get_discount|floatformat:2 }}</td>
            </tr>
            {% endif %}
            <tr class="total">
              <td>Загалом</td>
              <td colspan="3"></td>
              <td>
                {{ cart.get_total_price_after_discount|floatformat:2 }}
              </td>
              <td></td>
            </tr>
        </tbody>
      </table>

      <p>Використати купон на знижку:</p>
      <form action="{% url 'coupon:apply' %}"
            method="post">
        {% csrf_token %}
        {{ coupon_apply_form.code }}
        <input type="submit" value="Оновити">
      </form>
    </div>
    <div class="row">
      <div class="four columns">
        <a href="{% url 'shop:main_page' %}" class="button u-full-width">Продовжити</a>
      </div>
      <div class="four columns">
        <a href="{% url 'order:create' %}" class="button button-primary u-full-width">Оформити замовлення</a>
      </div>
      <div class="four columns">
        <a href="{% url 'cart:clear' %}" class="button u-full-width">Очистити кошик</a>
      </div>
    </div>
  </div>
</section>
{% endblock %}