_project/urls.py
from django.apps import apps as django_apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^staff_area/', include('apps.shop.urls_for_staff',
                                 namespace='staff_area')),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^search/', include('haystack.urls')),

    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^order/', include('apps.orders.urls', namespace='order')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^coupons/', include('apps.coupons.urls', namespace='coupon')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^', include('apps.shop.urls', namespace='shop'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rosetta_is_installed = django_apps.is_installed('rosetta')
if rosetta_is_installed:
    urlpatterns = [
        url(r'^rosetta/', include('rosetta.urls')),
    ] + urlpatterns

# ___________________________________________________________________________
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

apps/coupons/urls.py
from django.conf.urls import url

from . import views, views_for_staff

urlpatterns = [
    url(r'^apply/$',
        views.coupon_apply,
        name='apply'),

    url(r'^list/$',
        views_for_staff.coupons,
        name='list'),
    url(r'^create/$',
        views_for_staff.coupon_create,
        name='create'),
]

apps/shop/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main, name='main_page'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^product_detail/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<manufacturer_slug>[-\w]+)/$',
        views.product_list_by_manufacturer,
        name='product_list_by_manufacturer'),
]

templates/_includes/main_menu.html
{% load static %}
{% load i18n %}

<nav class="main-nav" role="navigation">

  <!-- Mobile menu toggle button (hamburger/x icon) -->
  <input id="main-menu-state" type="checkbox" />
  <label class="main-menu-btn" for="main-menu-state">
    <span class="main-menu-btn-icon"></span> Toggle main menu visibility
  </label>

    <a href="{% url 'shop:main_page' %}"><img src="{% static 'img/logo.png' %}"></a>

  <ul id="main-menu" class="sm sm-clean">
    <li class="{% if not category.slug %}current-menu-item{% endif %}">
      <a href="{% url 'shop:main_page' %}">
        <i class="fa fa-home" aria-hidden="true"></i>
      </a>
    </li>
    {% for cat in menu_categories %}
      {% if not cat.has_parent_category %}
      <li class="{% if category.slug == cat.slug %}current-menu-item{% endif %}">
        <a href="{{ cat.get_absolute_url }}">{{ cat }}</a>
        {% if cat.subcategories %}
        <ul>
          {% for cat_ in cat.subcategories %}
          <li>
            <a href="{{ cat_.get_absolute_url }}">{{ cat_ }}</a>
            {%if cat_.subcategories %}
            <ul>
              {% for cat__ in cat_.subcategories %}
              <li><a href="{{ cat__.get_absolute_url }}">{{ cat__ }}</a></li>
              {% endfor %}
            </ul>
            {% endif %}
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </li>
      {% endif %}
    {% endfor %}
    <li class="separator"><a>|</a></li>
    <li class="">
      <a href="#">
        {% trans 'Contacts' %}
      </a>
    </li>
  </ul>
</nav>

templates/_includes/render_fields.html
{% load form_filters %}

{{ form.non_field_errors }}

{% for field in form_fields %}
<div class="row">
  <div class="two columns">
    {% if not field|is_hidden %}
      {{ field.label_tag }}
    {% endif %}
  </div>
  <div class="five columns">
    {{ field|addclass:"u-full-width" }}
  </div>
  {% if field.errors %}
  <div class="five columns error">{{ field.errors }}</div>
  {% endif %}
</div>
{% endfor %}

templates/_includes/staff_area_menu.html
<a href="">Товари</a>
<a href="{% url 'staff_area:categories' %}">Категорії</a>
<a href="{% url 'staff_area:manufacturers' %}">Виробники</a>
<a href="{% url 'coupon:list' %}">Купони</a>