_project/urls.py
from django.apps import apps as django_apps
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^staff_area/', include('apps.shop.urls_for_staff',
                                 namespace='staff_area')),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    url(r'^search/', include('haystack.urls')),

    url(r'^cart/', include('apps.cart.urls', namespace='cart')),
    url(r'^order/', include('apps.orders.urls', namespace='order')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^coupons/', include('apps.coupons.urls', namespace='coupon')),
    url(r'^payment/', include('apps.payment.urls', namespace='payment')),
    url(r'^', include('apps.shop.urls', namespace='shop'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rosetta_is_installed = django_apps.is_installed('rosetta')
if rosetta_is_installed:
    urlpatterns = [
        url(r'^rosetta/', include('rosetta.urls')),
    ] + urlpatterns

# ___________________________________________________________________________
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

apps/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),

    url(r'^user_profile/$', views.user_profile, name='user_profile'),
]

apps/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.cart_detail,
        name='detail'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove_product,
        name='remove_product'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add_product,
        name='add_product'),
    url(r'^clear/$',
        views.cart_clear,
        name='clear')
]

apps/users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title%}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <link rel='shortcut icon' type='image/x-icon'
        href="{{ PORTAL_URL }}{% static 'img/favicon.ico' %}" />

  <!-- Styles -->
  <link rel="stylesheet"
        href=https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css />
  <link rel="stylesheet"
        href="{{ PORTAL_URL }}{% static 'css/skeleton.css' %}" />
  {% block extra_css %}{% endblock %}
  <link rel="stylesheet"
        href="{{ PORTAL_URL }}{% static 'css/sm-clean.css' %}" />
  <link rel="stylesheet"
        href="{{ PORTAL_URL }}{% static 'css/main.css' %}" />

</head>
<body style="background-image: url({% static 'img/02.png' %});">
  <section class="container" id="top">
    <div class="wrapper">
      <div class="row">
        <div class="six columns">
          {% if not request.user.is_authenticated %}
          <a href="{% url 'accounts:login' %}">{% trans 'Log in' %}</a> |
          <a href="{% url 'accounts:register' %}">{% trans 'Register' %}</a>
          {% else %}
          {% trans 'Hello' %}, {{ request.user.username }} |
          <a href="{% url 'accounts:user_profile' %}" title="{% trans 'Profile' %}">
            <i class="fa fa-user" aria-hidden="true"></i></a>
          <a href="{% url 'accounts:logout' %}" title="{% trans 'Log out' %}">
            <i class="fa fa-sign-out" aria-hidden="true"></i></a>
          {% endif %}
        </div>
        <div class="six columns">
          <div class="cart u-pull-right">
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
            <i class="fa fa-shopping-basket" aria-hidden="true"></i>
            <a href="{% url 'cart:detail' %}"> ({{ total_items }})</a>
            {% else %}
              <i class="fa fa-shopping-basket" aria-hidden="true"></i>
            {% endif %}
            {% endwith %}
          </div>
        </div>
      </div>
    </div>
  </section>

  {% block main_menu %}
  <section class="container" id="main_menu">
    <div class="wrapper">
      {% include '_includes/main_menu.html' %}
    </div>
  </section>
  {% endblock main_menu %}

  {% block content %}{% endblock %}

  <section class="container" id="bottom">
    <div class="wrapper">
      <div class="copyright">Copyright © {% now 'Y' %} | Online Shop</div>
    </div>
  </section>

  <!-- <script src="https://use.fontawesome.com/62626c0a50.js"></script> -->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"
          integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
          crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'js/jquery.smartmenus.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</body>
</html>